# Generated by Django 4.1.1 on 2022-09-26 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartmeta',
            fields=[
                ('client_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(default='Mr/Mrs', max_length=100)),
                ('deadline', models.DateField(default='2022-09-23')),
                ('term_time', models.TimeField(default='10:10:10')),
                ('descrition', models.TextField(default='no description')),
                ('priority', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('client_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('client_name', models.CharField(default='no name', max_length=100)),
                ('client_number', models.CharField(default='no number', max_length=100)),
                ('client_address', models.CharField(default='no address', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('product_id', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('term_time', models.TimeField()),
                ('descrition', models.TextField()),
                ('priority', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(default='Default product')),
                ('price', models.IntegerField(default=0.0)),
                ('category', models.CharField(default='Others', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Clientcarts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.clients')),
            ],
        ),
    ]
