# Generated by Django 4.1.1 on 2022-09-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='client_address',
            field=models.CharField(default='Earth', max_length=100),
        ),
        migrations.AlterField(
            model_name='clients',
            name='client_name',
            field=models.CharField(default='Human', max_length=100),
        ),
        migrations.AlterField(
            model_name='clients',
            name='client_number',
            field=models.CharField(default='+1234567890', max_length=100),
        ),
    ]
