# Generated by Django 4.1.1 on 2022-09-26 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_descrition_cartmeta_descrpition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmeta',
            old_name='descrpition',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='descrpition',
            new_name='description',
        ),
    ]
