# Generated by Django 4.1.1 on 2022-09-27 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_descrpition_cartmeta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcarts',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.products'),
        ),
    ]
