# Generated by Django 4.1.1 on 2022-09-27 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_product_id_clientcarts_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmeta',
            name='client_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shop.clients'),
        ),
    ]
