# Generated by Django 4.1.1 on 2022-09-27 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_cartmeta_client_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmeta',
            old_name='client_id',
            new_name='client',
        ),
    ]
