# Generated by Django 4.1.1 on 2022-09-27 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_orders_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedgoods',
            name='order_id',
            field=models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='shop.orders'),
        ),
        migrations.AlterField(
            model_name='orderedgoods',
            name='product_id',
            field=models.OneToOneField(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='shop.products'),
        ),
    ]
