# Generated by Django 4.1.1 on 2022-10-06 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0010_alter_orderedgoods_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmeta',
            name='client',
            field=models.OneToOneField(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shop.clients'),
        ),
        migrations.RenameField(
            model_name='cartmeta',
            old_name='client',
            new_name='client_id',
        ),
        migrations.AlterField(
            model_name='clientcarts',
            name='client',
            field=models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='shop.clients'),
        ),
        migrations.RenameField(
            model_name='clientcarts',
            old_name='client',
            new_name='client_id',
        ),
        migrations.AlterField(
            model_name='clientcarts',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='shop.products'),
        ),
        migrations.RenameField(
            model_name='clientcarts',
            old_name='product',
            new_name='product_id',
        ),
        migrations.CreateModel(
            name='ShopUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.OneToOneField(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='shop.clients')),
                ('username', models.OneToOneField(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
