# Generated by Django 4.1.1 on 2022-10-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_categories_id_alter_categories_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(default='New', max_length=100),
        ),
    ]
