# Generated by Django 4.1.1 on 2022-10-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(default='Other', max_length=100),
        ),
    ]
