# Generated by Django 4.1.1 on 2022-10-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_products_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'ordering': ['client_name'], 'verbose_name': 'Shop clients', 'verbose_name_plural': 'Shop clients'},
        ),
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='client_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='TG identifikator'),
        ),
    ]
