# Generated by Django 4.1.1 on 2022-10-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_clients_options_categories_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
